### ISSUE TITLE
Bruuuuuuuuuuuhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by PitamahBhishma-0** [iamabhas/population-bar-graph#1]
null

**Comment by PitamahBhishma-0** [comment]
solved

**Comment by PitamahBhishma-0** [comment]
hello

**Comment by PitamahBhishma-0** [comment]
can someone reply?

**Comment by iamabhas** [comment]
shut up bro

**Comment by PitamahBhishma-0** [comment]
oh come on how rude can u be?

**Comment by PitamahBhishma-0** [comment]
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by iamabhas** [comment]
bro you're a debian user . I'm a arch user btw . I dont like debian users

**Comment by PitamahBhishma-0** [comment]
oh now u wanna start a war then?

**Comment by iamabhas** [comment]
yeas bro i want war

**Comment by iamabhas** [comment]
Stop changing the title . Also i am anti rickroll.I dont get rickrolled

**Comment by PitamahBhishma-0** [comment]
sudo apt start war

**Comment by iamabhas** [comment]
sudo pacman -S get_weapons

**Comment by PitamahBhishma-0** [comment]
errror: command not found 😆.
You have no power here.

**Comment by PitamahBhishma-0** [comment]
bro i am dropping the weapon
halt- weapon

**Comment by iamabhas** [comment]
Error detected : War ended 
Friendship Acquired !
War Ended !
Debian and Arch combined !!

**Comment by PitamahBhishma-0** [comment]
#issue_closed

**Comment by iamabhas** [comment]
#thank_you_bozo
